### ISSUE TITLE
Tagcomplete messes with keyboard input on cyrillic layout

### ISSUE THREAD

**Issue by Self-Perfection** [gesellkammer/zim-plugins#2]
With English layout tagcomplete plugin works fine.

But if I try to enter Russian tag it gets replaced with Arabic symbols. For instance what if I'd like to enter tag `@досуг`.

1. With English keyboard layout I type `@` (there is no `@` key when russian layout is active)
2. Then I switch to Russian layout. Does not matter how: by hotkey (Caps Lock) or by clicking layout icon in notification area
3. Then I type `досуг`
4. This is what appears instead:` @︈ۄۏۓەۇ `

**Comment by gesellkammer** [comment]
Thanks for reporting. Your problem seems out of scope of this plugin, 
but a work around I imagine in your case would be modifying your 
keyboard layout to be able to type the @ sign without switching keyboard 
layout

**Comment by Self-Perfection** [comment]
@gesellkammer nope this is a bug in tagcomplete plugin and I managed to find a solution - see #3 :stuck_out_tongue:
