### ISSUE TITLE
let spacebar create tag if not already in the list

### ISSUE THREAD

**Issue by mooseyboots** [gesellkammer/zim-plugins#4]
just discovered yr plugin and it's v helpful, especially for avoiding creating lots of similar tags.

one problem i found is that if the tag i'm typing is not found in the list, when i hit spacebar the tag does not become active in zim. ideally tab wd let me choose from the filtered list and spacebar would let me close the autocomplete window and create a new tag just as zim normally does without autocompletion.

**Comment by mooseyboots** [comment]
so how do you deal with this? your plugin opens a window every time a @ is written. how do you add new tags with the window open? for me your plugin makes creating new tags very difficult.

was my feedback that bad that you close this without any comment?

**Comment by gesellkammer** [comment]
https://imgur.com/a/yNFXOi6
