### ISSUE TITLE
autocomplete window drawn over the top of the tag being created

### ISSUE THREAD

**Issue by mooseyboots** [gesellkammer/zim-plugins#5]
zim 072 on debian/xfce

sometimes when creating a tag the autocomplete window is offset, like way off to the right, which is not rly a problem, but sometimes it is drawn right over the tag being created, such that the user cannot see what they are typing. very frustrating.

**Comment by gesellkammer** [comment]
Can you post a screenshot? It works for me in gnome and kde. But notice that this has been brought up before (#1) and my answer remains: if I can't reproduce this I can't fix it. You are welcome to post a fix as a PR.

**Comment by mooseyboots** [comment]
![autocompletetag](https://user-images.githubusercontent.com/66318400/83550991-3d448700-a4f7-11ea-8c3f-ec253c109717.jpg)

the cursor and begun tag on the line under the date.

**Comment by mooseyboots** [comment]
i saw the other issue. i thought mayb worth mentioning that i have it too. if i had any idea how to go about modifying the behaviour of it, i would have a look. but i'm not that capable. if you aren't able to do anything, do you have a sense of where i might look?
